#theme: jekyll-theme-cayman
name: Just another Ruby porter,
title: Just another Ruby porter,
timezone: Asia/Tokyo
markdown: kramdown
kramdown:
  input: GFM
  #gfm_quirks: true
  hard_wrap: true
baseurl: /xblog
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      permalink: /:year-:month-:day-:title/
