#theme: jekyll-theme-cayman
name: Just another Ruby porter,
title: Just another Ruby porter,
timezone: Asia/Tokyo
markdown: GFM
baseurl: htts://eban.github.io/xblog/
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      permalink: /:year-:month-:day-:title:output_ext
