#theme: jekyll-theme-cayman
name: Just another Ruby porter,
title: Just another Ruby porter,
lang: ja
paginate: 10 # amount of posts to show
paginate_path: /page:num/
theme: minima
timezone: Asia/Tokyo
baseurl: /xblog
url: https://eban.github.io/xblog
plugins:
  - jekyll-feed
feed:
  path: feed.xml

markdown: kramdown
kramdown:
  input: GFM
  #gfm_quirks: true
  hard_wrap: true

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      permalink: /:year-:month-:day-:title/
